### ISSUE TITLE
Depthwise atrous convolution

### ISSUE THREAD

**Issue by DecentMakeover** [alexandrosstergiou/keras-DepthwiseConv3D#2]
Hi

Thanks for sharing your work.

If i increase the dilation rate, then the operation would be depthwise atrous convolution correct?

as a side question, any idea why when using dilation rate >1 i cannot use stride >1?

Thanks

**Comment by alexandrosstergiou** [comment]
Yes, the code essentially breaks the input volume to sub-shapes with channel size 1 and iterates a 3DConv for each of the single-channel volumes. So any operation that will normally be done over the entire input, is now performed in a channel-wise fashion (currently looking on ways of removing the naive loop).

Could you provide some more information about the error or your the stack trace?

Best,

**Comment by DecentMakeover** [comment]
Lazy to post stack trace, currently i found a workaround.

Thanks  a lot for your response.
