### ISSUE TITLE
channels_last support ?

### ISSUE THREAD

**Issue by ltetrel** [alexandrosstergiou/keras-DepthwiseConv3D#3]
Hi,

In your readme you are saying that your function supports only channels_first volume, but in your code I see that you are using channel_last for`self._data_format = "NDHWC"` ? So is your code supporting channels_last ?

Thanks for your contribution.

**Comment by alexandrosstergiou** [comment]
Yes, since the last commit, the `DepthwiseConv3D` class also supports channels_last inputs. So you can use it as a standard Keras layer without the need of transforming the activation map tensors before using it.

Best,
