### ISSUE TITLE
[question] Is this a channel-wise convolution ?

### ISSUE THREAD

**Issue by ltetrel** [alexandrosstergiou/keras-DepthwiseConv3D#4]
Hi,

I just needed a clarification about your function.
In my application I have a tensor that is the concatenation of two 3D volumes, so size [height, width, depth, n_channels=2]. I want to apply `n_filters` 3D kernels [3, 3, 3] to each of the volumes, so the output tensor would be [new_height, new_width, new_depth, n_filters, n_channels=2], is this what your function does ?

Thanks,

**Comment by alexandrosstergiou** [comment]
Based on your description, you should be able to do both channel-wise 3D Convolutions (default method) and 3D Conv in groups of channels. The only change that you should do, if you want to use the code as it is, is to reshape your (5D) input volume to a more standardised format e.g. `(batch,)depth,height,width,channels` or `(batch ,)channels,depth,height,width`. 

Best,
